version: '3'
services:
  api:
    build: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "9999:9999"
    networks:
      - api
      - backend
  populator:
    build: populator
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
    networks:
      - backend
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - "/data"

networks:
  api:
  backend:
   internal: true
